#!/usr/bin/env fish

source ./secrets.fish
set user_id "79132105@N04"
set method "flickr.people.getPublicPhotos"

set output (curl -s "https://api.flickr.com/services/rest/?api_key=$api_key&format=json&nojsoncallback=1&method=$method&user_id=$user_id&extras=url_l,tags,date_taken,path_alias")

mustache (echo $output | jq '.photos.photo|map(select(.tags | contains("portfolio"))) | { "photos": . } ' | psub) template/index.mustache.html
